/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    static public boolean arrayLimit(int[] arr) { //check array limit between 1 and 6
        for (int number : arr) {
            if (number > 6 || number < 1)
                return false;

        }
        return true;
    }


    @Test
    void rollTest() {
        assertEquals(Library.roll(5).length, 5); // check the length correctly
        assertTrue(arrayLimit(Library.roll(10))); //check if the returned array contains any number bellow 1 and more than 6
    }

    @Test
    void containsDuplicatesTest() { // i was thinking of adding all the data type for example string not just integer but i didn't know how
        Integer[] containDubsArray = {
                1, 2, 3, 4, 5, 5, 7, 8
        };
        Integer[] noDubsArray = {1, 2, 3, 4, 5, 6};
        assertTrue(Library.containsDuplicates(containDubsArray));
        assertFalse(Library.containsDuplicates(noDubsArray));
    }

    @Test
    void calculatingAveragesTest() {
        int[] arrayToAvg = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};// avg = 5.5
        int[] scndArrayToAvg = {1, 3, 7, 6, 8, 1, 5, 0, 15, 22, 35, 78, 99, 105, 258}; // avg = 42.87
        assertEquals(Library.calculatingAverages(arrayToAvg), 5.5);
        assertEquals(Library.calculatingAverages(scndArrayToAvg), 42.87F); // F is stand for float 
    }

    @Test
    void arraysOfArraysTest() {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[] actualArray = {55, 54, 60, 53, 59, 57, 61};
        assertArrayEquals(Library.arraysOfArraysAverages(weeklyMonthTemperatures), actualArray);
    }

}
