/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.util.Iterator;

public class Library {
    public static void main(String[] args) {
        Restaurant mac = new Restaurant("Macdonalds", 5, "$");
        System.out.println("Initialize mac restaurant =>> " + mac.toString());
        Review review = new Review("Nice res", "Mamoun", 0);
        System.out.println("set up normal review with no restaurant associated =>> " + review.toString());

        System.out.println("the restaurant will no cahnge after the review becuase we didn't add it =>> " + mac.toString());
        mac.addReview(review);
        System.out.println("Added the review to the mac restaurant =>> " + mac.toString());

        System.out.print("if you try to add the same review to the same restaurant => ");
        mac.addReview(review);

        System.out.println("let's create user and make him make review on mac");
        User mamoun = new User("mamoun");
        Review userReview = new Review(mac, "good", mamoun, 2);
        System.out.println("The user is " + mamoun.getName() + " and his review is" + userReview.toString());
        System.out.println("the restaurant after the user review =>> " + mac.toString());

        System.out.print("If the same user to add multi review =>> ");
        Review userReviewq = new Review(mac, "good", mamoun, 2);

        System.out.println("The restaurant rating will not change due that they refuse multiable review from the same user =>> " + mac.toString());

    }
}
